### ISSUE TITLE
ENotImplemented: SQLite3 function not implemented

### ISSUE THREAD

**Issue by sharkibm** [afpineda/Embedded-SQLite3-for-Delphi#1]
Have this being this tested with RAD 12? I'm always  getting getting error: ENotImplemented: SQLite3 function not implemented.

**Comment by afpineda** [comment]
Sorry. I have no access to RAD 12, so I can't tell.

The exception `ENotImplemented` is caused by the dynamic linkage of an unexpected version of "Sqlite3.dll". Currently, version 3.42.0 is expected. That means that some API call has been removed from the SQLite API.

Use the debugger to know which API call is raising it, at [SQLite3.Core.Functions.pas](https://github.com/afpineda/Embedded-SQLite3-for-Delphi/blob/main/source/SQLite3.Core.Functions.pas). 
Put a breakpoint in `procedure DoInitialize;` as well. Maybe, your code is trying to link another pre-existing version of "Sqlite3.dll" at the temporary folder, or the default PATH.
